name: Node.js Package

on:
  push:
    branches: [element]
  pull_request:
    branches: [element]

jobs:
  release:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - name: checout
        uses: actions/checkout@v2
      - name: node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org
      - name: install
        run: cd packages/element && npm ci
      - name: build
        run: lerna run build --scope=@htmlplus/element
      - name: publish
        run: cd packages/element/dist && npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
